### ISSUE TITLE
Stretching images according to device resolution

### ISSUE THREAD

**Issue by mannoeu** [JonathanSaan/PokeSaan#1]
Hello how are you?

Passing by to congratulate you on the project. I don't know if you're open to suggestions, but you could add `objectFit="contain"` property in next/image to prevent image stretching in:

https://github.com/JonathanSaan/PokeSaan/blob/b3917be8781c1972ec7366415c9a2a670057452b/components/PokemonList.tsx#L28

https://github.com/JonathanSaan/PokeSaan/blob/b3917be8781c1972ec7366415c9a2a670057452b/pages/pokemon/%5Bname%5D.tsx#L74

[ref](https://nextjs.org/docs/api-reference/next/image#fill)

---
<p align="center">
<img src="https://user-images.githubusercontent.com/53797821/136099250-f18024f8-7c37-4033-bc5b-4f1327d3588a.gif" width="200" />
</p>
<p align="center" style="text-style: italic">
See you space cowboy
</p>

**Comment by JonathanSaan** [comment]
Hi, I'm great

thanks for the suggestion, I'll put it in my code now :)
